// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD5cXmij6n3T5WpMupyYaePmoF6B3omnF8',
    appId: '1:747739668486:web:46065ecaf3cb5611e1e387',
    messagingSenderId: '747739668486',
    projectId: 'tllp-connect',
    authDomain: 'tllp-connect.firebaseapp.com',
    storageBucket: 'tllp-connect.firebasestorage.app',
    measurementId: 'G-G4DESBJYJF',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC3fHSkg9V2o1l0ceR4cRHL9W8qXzcAcRY',
    appId: '1:747739668486:android:2f692b23a04dbb69e1e387',
    messagingSenderId: '747739668486',
    projectId: 'tllp-connect',
    storageBucket: 'tllp-connect.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBnZlEanitKobUvicsU0nRoylyXo7VSslM',
    appId: '1:747739668486:ios:0e13cdb726de76b8e1e387',
    messagingSenderId: '747739668486',
    projectId: 'tllp-connect',
    storageBucket: 'tllp-connect.firebasestorage.app',
    iosBundleId: 'com.qsyncai.mpcm',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBnZlEanitKobUvicsU0nRoylyXo7VSslM',
    appId: '1:747739668486:ios:0e13cdb726de76b8e1e387',
    messagingSenderId: '747739668486',
    projectId: 'tllp-connect',
    storageBucket: 'tllp-connect.firebasestorage.app',
    iosBundleId: 'com.qsyncai.mpcm',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyD5cXmij6n3T5WpMupyYaePmoF6B3omnF8',
    appId: '1:747739668486:web:b8f21d9ddbfc4f53e1e387',
    messagingSenderId: '747739668486',
    projectId: 'tllp-connect',
    authDomain: 'tllp-connect.firebaseapp.com',
    storageBucket: 'tllp-connect.firebasestorage.app',
    measurementId: 'G-NRMCRBNCNV',
  );
}
